/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetsSetNumRouteImport } from './routes/sets/$setNum'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsSetNumRoute = SetsSetNumRouteImport.update({
  id: '/sets/$setNum',
  path: '/sets/$setNum',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sets/$setNum': typeof SetsSetNumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sets/$setNum': typeof SetsSetNumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sets/$setNum': typeof SetsSetNumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collection' | '/login' | '/register' | '/sets/$setNum'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collection' | '/login' | '/register' | '/sets/$setNum'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/login'
    | '/register'
    | '/sets/$setNum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SetsSetNumRoute: typeof SetsSetNumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets/$setNum': {
      id: '/sets/$setNum'
      path: '/sets/$setNum'
      fullPath: '/sets/$setNum'
      preLoaderRoute: typeof SetsSetNumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SetsSetNumRoute: SetsSetNumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
